[profile.default]
src = "src"
out = "out"
libs = ["lib"]



remappings = [
    '@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts@4.8.3/=lib/openzeppelin-contracts-4.8.3/contracts/',
    '@ccip/contracts/=lib/chainlink-ccip/chains/evm/contracts/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
